### ISSUE TITLE
Is there an article that introduces the principles of your framework? In particular, how can GDBT be federated

### ISSUE THREAD

**Issue by bigdaronlee163** [Xtra-Computing/FedTree#34]

**Comment by QinbinLi** [comment]
Hi @bigdaronlee163 ,

Thanks for your interest in our work! We are working on the draft of the system and we will upload it to this Github page once it is finished. For the federated GBDTs, there are some existing studies ([ref1](https://arxiv.org/pdf/1911.04206.pdf), [ref2](https://ieeexplore-ieee-org.libproxy1.nus.edu.sg/document/8486352)) for your reference.

**Comment by wxli0** [comment]
Hi @QinbinLi, ref1 discusses the case of horizontal federated learning, and I could not open ref2. Is there an article or a doc that introduces the mechnism implemented in this repo for vertical federated learning? Thank you!

**Comment by QinbinLi** [comment]
Hi @wxli0 ,

You may refer to [here](https://fedtree.readthedocs.io/en/latest/Frameworks.html) for a brief explanation on vertical FL. You may also refer to [secureboost](https://arxiv.org/abs/1901.08755) and its [document](https://github.com/FederatedAI/FATE/blob/master/doc/federatedml_component/ensemble.md), which has a similar design as ours.

**Comment by QinbinLi** [comment]
@wxli0  Right. FedTree currently stores the global model and sends it to all parties.
