### ISSUE TITLE
Log prediction score for vertical FL

### ISSUE THREAD

**Issue by wxli0** [Xtra-Computing/FedTree#39]
I wanted to see the prediction score and predicted labels of the test dataset in vertical FL. After adding some LOG(INFO) to the [main.py](https://github.com/Xtra-Computing/FedTree/blob/main/src/FedTree/main.cpp#L255), [GBDT::predict_score_vertical](https://github.com/Xtra-Computing/FedTree/blob/main/src/FedTree/Tree/gbdt.cpp#L89) and [GBDT::predict_raw](https://github.com/Xtra-Computing/FedTree/blob/main/src/FedTree/Tree/gbdt.cpp#L111), I found the the logs after [model.host_data()](https://github.com/Xtra-Computing/FedTree/blob/main/src/FedTree/Tree/gbdt.cpp#L126) cannot be printed out to console. 

Could someone please suggest how to resolve the issue? Thank you very much!

**Comment by QinbinLi** [comment]
Hi @wxli0 ,

`predict_score_vertical` calls `predict_raw_vertical` instead of `predict_raw`. Maybe you put LOG(INFO) in a wrong place?

**Comment by wxli0** [comment]
Thank you very much for your help! I made some changes in your code which might break the flow. I reverted back to the original copy, and the problem has been resolved. Thanks again!
