### ISSUE TITLE
Using a pretrained horizontal FL classification model on the Python interface + Local datasets for FLClassifier?

### ISSUE THREAD

**Issue by abrahamcanafe** [Xtra-Computing/FedTree#40]
Is it possible to load a pretrained horizontal FL `.model` file to an [FLClassifier](https://github.com/Xtra-Computing/FedTree/blob/00f0416f374ef1e3c1ae8fc976702c3e4d8f2346/python/fedtree/fedtree.py#L353) object on the Python interface and then use the [predict()](https://github.com/Xtra-Computing/FedTree/blob/00f0416f374ef1e3c1ae8fc976702c3e4d8f2346/python/fedtree/fedtree.py#L144) method to make new predictions, even if the pretrained model was generated via command line interface?

Alternatively, is there a way to use both the standalone build and the Python interface in order to train a horizontal FL model in which the clients supply their own local datasets? From my understanding of [fedtree.py](https://github.com/Xtra-Computing/FedTree/blob/main/python/fedtree/fedtree.py) and [scikit_fedtree.cpp](https://github.com/Xtra-Computing/FedTree/blob/main/src/FedTree/scikit_fedtree.cpp), it appears that [FLClassifier](https://github.com/Xtra-Computing/FedTree/blob/00f0416f374ef1e3c1ae8fc976702c3e4d8f2346/python/fedtree/fedtree.py#L353) can only simulate FL by partitioning a single dataset, rather than importing separate datasets from the local parties. (Is this correct?)
___
I am trying to train a horizontal FL classification FedTree model using local datasets supplied by each of the individual parties. I can run the [CLI Distributed Horizontal FedTree example](https://github.com/Xtra-Computing/FedTree#distributed-horizontal-fedtree) (as well as [classifier_example.py](https://github.com/Xtra-Computing/FedTree/blob/main/python/examples/classifier_example.py)) just fine, but it's not clear to me how I can make new predictions after loading the `.model` files with the Python API. When I use the [predict()](https://github.com/Xtra-Computing/FedTree/blob/00f0416f374ef1e3c1ae8fc976702c3e4d8f2346/python/fedtree/fedtree.py#L144) method right after creating an FLClassifier object and loading a model via [load_model()](https://github.com/Xtra-Computing/FedTree/blob/00f0416f374ef1e3c1ae8fc976702c3e4d8f2346/python/fedtree/fedtree.py#L257), my program immediately terminates (unless I have trained a new model with the [fit()](https://github.com/Xtra-Computing/FedTree/blob/00f0416f374ef1e3c1ae8fc976702c3e4d8f2346/python/fedtree/fedtree.py#L93) method, which would defeat the purpose of what I am trying to do).
___
Any help would be greatly appreciated!

**Comment by QinbinLi** [comment]
@abrahamcanafe ,

I have fixed this issue. Now you should be able to use the Python interface to load the model trained with CLI and conduct prediction. Also, we will improve the python interface so that it supports importing separate datasets in the distributed setting in the future. Thanks!

**Comment by abrahamcanafe** [comment]
> @abrahamcanafe ,
> 
> I have fixed this issue. Now you should be able to use the Python interface to load the model trained with CLI and conduct prediction. Also, we will improve the python interface so that it supports importing separate datasets in the distributed setting in the future. Thanks!

Thanks for quick response! I was indeed able to use the Python interface to load a model from CLI.
