### ISSUE TITLE
Unsupported CSV format

### ISSUE THREAD

**Issue by henrydrp10** [Xtra-Computing/FedTree#41]
Hello,

For some reason I am getting unsupported CSV format, is there anything I might have missed? I am trying to run the first of the 4 distributed parties. My test dataset and my train partitions share the same format, so I don't know what might be happening:

henry:FedTree$ ./build/bin/FedTree-distributed-server ./examples/henry/fd001_server.conf
2022-08-02 15:57:33,024 INFO distributed_server.cpp:1616 : server init completed.

*in another terminal tab:*
henry:FedTree$ ./build/bin/FedTree-distributed-party ./examples/henry/fd001_party0.conf 0
unsupported csv format

------------------------------------------------------

CSV files:

test.csv
id y x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11
0 112 642.58 1581.22 1398.91 554.42 2388.08 47.23 521.79 2388.06 8.4024 393 38.81 23.3552
1 98 642.55 1586.59 1410.83 553.52 2388.1 47.67 521.74 2388.09 8.4505 391 38.81 23.2618
2 69 642.88 1589.75 1418.89 552.59 2388.16 47.88 520.83 2388.14 8.4119 395 38.93 23.274
3 82 642.78 1594.53 1406.88 552.64 2388.13 47.65 521.88 2388.11 8.4634 395 38.58 23.2581
4 91 642.27 1589.94 1419.36 553.29 2388.1 47.46 521.0 2388.15 8.4362 394 38.75 23.4117
5 93 643.05 1586.94 1404.49 553.73 2388.14 47.51 521.56 2388.15 8.4452 393 38.91 23.3269
6 91 642.1 1589.59 1413.57 553.42 2388.04 47.32 522.32 2388.07 8.4028 393 38.91 23.2763

party0.csv
id y x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11
479 178 642.04 1584.2 1398.13 553.96 2388.06 47.14 522.24 2388.0 8.4207 391 38.96 23.3205
480 177 642.66 1587.04 1398.62 554.76 2388.05 47.35 522.03 2388.01 8.3949 390 39.07 23.4369
481 176 642.07 1580.75 1401.1 554.51 2388.03 46.94 522.16 2388.01 8.382 393 39.03 23.3162
482 175 642.5 1580.12 1395.76 554.48 2388.07 47.44 522.31 2388.07 8.394 391 38.94 23.4901
483 174 641.97 1581.48 1394.05 554.14 2388.01 47.16 522.0 2388.03 8.4233 391 38.9 23.419
484 173 642.65 1581.26 1397.98 554.86 2388.08 47.12 522.58 2388.08 8.4126 392 39.04 23.4656
485 172 642.62 1583.68 1405.76 554.29 2388.06 47.26 522.08 2388.01 8.4369 393 39.03 23.4051

**Comment by QinbinLi** [comment]
Hi @henrydrp10 ,

Can you use comma to separate values instead of space and try again? Note that CSV is for Comma-Sperated Values. Thanks!

**Comment by henrydrp10** [comment]
Thank you!
