### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by caijicopy** [Xtra-Computing/FedTree#46]
在cmake..的过程中遇到版本问题，我是3.3.2的版本却不符合条件，我尝试更改cmakelist文件，但是TRust中的条件显示只有3.15-3.18.请问是只能用3.15-3.18的版本嘛

**Comment by QinbinLi** [comment]
Hi @caijicopy ,

cmake版本要求至少>=3.15，你可以本地安装新的cmake版本然后加到环境变量里
