### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by relinda2019** [Xtra-Computing/FedTree#50]
Mac 上安装时，最后一条命令   make -j出错，如下所示。请问各位老师这个怎么解决呢？多谢
![fedtree_1](https://user-images.githubusercontent.com/39260479/200295571-74c7e99b-ae4f-42e6-baf2-df5cc837f361.png)
![fedtree_2](https://user-images.githubusercontent.com/39260479/200295591-bede288f-baca-4c1a-a496-0b036f1bf54d.png)

**Comment by QinbinLi** [comment]
Hi @relinda2019 ,

You can pull the latest version and try again. In the new version, we require gRPC as a prerequisite and you can follow [here](https://grpc.io/docs/languages/cpp/quickstart/) to install gRPC before installation of FedTree.
