### ISSUE TITLE
Specify Data Partition in Horizontal Federated Tree Training

### ISSUE THREAD

**Issue by WilliamLindskog** [Xtra-Computing/FedTree#53]
Hi,

first, thank you for this project! 

I am running FedTree on one computer and would like to assign each party (currently 2) one data set (sample of whole data set) to train on. I am running the python code and see that in fedtree.py there is a variable _path_, however it doesn't seem to be doing anything. How can I achieve this in stand-alone simulation? Is there another way to assign each party their local data set? 

Best regards,
W

**Comment by QinbinLi** [comment]
Hi @WilliamLindskog ,

You can specify the local dataset with command-line interface using `data` parameter, where you can specify the multiple paths to the local datasets separated with comma. For example, if you write a configuration file with the following parameters, it will load local datasets a and b as two parties. Currently the Python interface does not support this feature and can only load a single dataset for partition and simulation. We will add this feature in Python interface later.

```
data=a,b
n_parties=2
mode=horizontal
```
