### ISSUE TITLE
A Problem in Build on Linux

### ISSUE THREAD

**Issue by momentNi** [Xtra-Computing/FedTree#54]
There's an error while Standalone Simulation installation:

>>>  cmake ..

-- Found OpenMP_C: -fopenmp
-- Found OpenMP_CXX: -fopenmp
-- Found OpenMP: TRUE
Complie without CUDA
-- Found OpenMP_CXX: -fopenmp
-- Found OpenMP: TRUE  found components: CXX
CMake Error at CMakeLists.txt:52 (find_package):
  Could not find a package configuration file provided by "Protobuf" with any
  of the following names:

    ProtobufConfig.cmake
    protobuf-config.cmake

  Add the installation prefix of "Protobuf" to CMAKE_PREFIX_PATH or set
  "Protobuf_DIR" to a directory containing one of the above files.  If
  "Protobuf" provides a separate development package or SDK, be sure it has
  been installed.

-- Configuring incomplete, errors occurred!

How can i fix this ? I can't run the next command 'make -j'

**Comment by QinbinLi** [comment]
Hi @momentNi ,

You may set `DISTRIBUTED` to OFF, i.e., use
```
cmake .. -DDISTRIBUTED=OFF
```
instead of `cmake ..`.

**Comment by momentNi** [comment]
Thank you! The problem has been solved and the given example works fine!
