### ISSUE TITLE
Is there any solution to bind `FedTree-train` program to specific cpu cores in standalone simulation?

### ISSUE THREAD

**Issue by DarkHighness** [Xtra-Computing/FedTree#56]
Hi,
first, thank you for this great project!

I am running FedTree on one docker container and would like to bind FedTree-train program to some specific cpus instead of using whatever it can takes, which may causes problem when it uses too much resource.

Best regards,
Twiliness

**Comment by QinbinLi** [comment]
Hi @DarkHighness ,

There are two solutions.

1. You can use `export OMP_NUM_THREADS=xxx` to specify the number of threads used before running FedTree. 
2. You can also use [taskset](https://man7.org/linux/man-pages/man1/taskset.1.html) command to specify the CPU used to run the fedtree program, e.g., `taskset -c 0-3 ./build/bin/FedTree-train examples/machine.conf` to use only CPUs 0-3 to run Fedtree.

**Comment by DarkHighness** [comment]
Thanks for your timely reply!

Solution 1 works fine.
