### ISSUE TITLE
Error imputing more than 10 different data paths (files - .csv) 

### ISSUE THREAD

**Issue by WilliamLindskog** [Xtra-Computing/FedTree#58]
Hi, 

when running horizontal FL, I set several data files to ``data`` as in my previous [issue](https://github.com/Xtra-Computing/FedTree/issues/53). It would seem, when working with Forest Cover Type data set, that adding more than 10 different paths leads to:

 ``*** stack smashing detected ***, terminated. `` 

Is there a way to scale this beyond 10 different paths or am I mainly limited by my hardware? 

Best regards,
W

**Comment by QinbinLi** [comment]
Hi @WilliamLindskog ,

I have tried more than 10 paths and it works fine. Did you pull the latest version of FedTree? In a previous [commit](https://github.com/Xtra-Computing/FedTree/commit/376c7de020a409a6a64d9acbe127dc451e8a978c), I have increased the capacity for the parser. You may try to increase the size of `val` and rebuild the library and try again.

**Comment by Junyi-99** [comment]
Hi, I also met the same problem.
