### ISSUE TITLE
Is it an alternative way to install NTL?

### ISSUE THREAD

**Issue by taokz** [Xtra-Computing/FedTree#60]
Thank you for your great work!

I would like to install NTL on a workstation (I can not get the sudo permission because of the policy), and I just run '''make install''' and got the following error.

'''
mkdir -p -m 755 /usr/local/include
rm -rf /usr/local/include/NTL
mkdir -m 755 /usr/local/include/NTL
mkdir: cannot create directory ‘/usr/local/include/NTL’: Permission denied
make: *** [install] Error 1
'''

I was wondering if it is an alternative way to install NTL, and if NTL is necessary for this library? I would appreciate your help. Thanks!

**Comment by QinbinLi** [comment]
Hi @taokz ,

Yes, you can install NTL to a specified directory by passing the option PREFIX. You may refer to [here](https://libntl.org/doc/tour-unix.html) for details. Then, you need to pass the location to option NTL_PATH when building FedTree library (e.g., cmake .. -DNTL_PATH="PATH_TO_NTL").

**Comment by taokz** [comment]
Hi @QinbinLi ,

Thank you for your quick reply! I've installed the NTL lib.
